' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/09/23 by mojtaba
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

Dim swSheetWidth As Double
Dim swSheetHeight As Double
Dim swAssembly As AssemblyDoc
Dim myModelView As Object
boolstatus = swApp.LoadFile2("D:\MS_Control_Project\SolidWorks\Stack\stack-1-3x30m-1.snapshot.1\AssemChimney1.3M.x_t", "")
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Take Snapshot
Dim swSnapShot As SnapShot
Set swSnapShot = Part.ModelViewManager.AddSnapShot("Home")
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, 0.08237320124622518613, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02246541852169777614, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05990778272452740305, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04493083704339555229, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08237320124622518613, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0973501469273570369, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05241930988396147767, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1048386197679229553, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05241930988396147767, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05241930988396147767, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08986167408679110458, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08237320124622518613, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05990778272452740305, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0973501469273570369, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04493083704339555229, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05241930988396147767, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08986167408679110458, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05241930988396147767, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.1123270926084888877, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02995389136226370153, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.08237320124622518613, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.05990778272452740305, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02995389136226370153, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.04493083704339555229, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, -0.06739625556509333537, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.04493083704339555229, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, -0.07488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.02246541852169777614, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06185010536754918797, -0.08237320124622518613, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.03744236420282962691, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.01497694568113185076, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.8627201165676865457, 14.39853311127944835, 0.3564467323289477463

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1374446785945537541, -0.08237320124622518613, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02246541852169777614, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02995389136226370153, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02246541852169777614, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02995389136226370153, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02995389136226370153, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02995389136226370153, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02246541852169777614, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05241930988396147767, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02246541852169777614, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01497694568113185076, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.6464700698655860833, 15.42172880576168836, -0.1500726274944668148

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.2233476027161498401, 0.4792622617962192244, -0.6265523076784234036, 11.76037162423870086, 0.2683935841445759252
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1340085616296899373, 0.05990778272452740305, -0.6265523076784234036, 11.76037162423870086, 0.2683935841445759252
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01497694568113185076, -0.6265523076784234036, 11.76037162423870086, 0.2683935841445759252
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.6265523076784234036, 11.76037162423870086, 0.2683935841445759252
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007488472840565925381, -0.6265523076784234036, 11.76037162423870086, 0.2683935841445759252

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02246541852169777614, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02995389136226370153, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04493083704339555229, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02246541852169777614, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01497694568113185076, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01497694568113185076, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.03744236420282962691, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02246541852169777614, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01497694568113185076, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.4043558373739983836, 14.40243133701608258, -0.4987615242374090485

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-1.026438814353497264, 13.67042213095373882, 0.4707166616295239692, 0.2950988985880138027, -0.2496831530909939811, -0.9222662105458924175, 0.03027039329457266101, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.9239862302886763246, 13.53299973359429487, 0.4224419829975545326, 0.2950988985880138027, -0.2496831530909939811, -0.9222662105458924175, 0.03027039329457266101, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(-1.252788719139601881, 13.88385624866484136, 0.6106596088893070373, 0.2950988985880138027, -0.2496831530909939811, -0.9222662105458924175, 0.03027039329457266101, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(-1.17351626672831344, 13.86113566907275185, 0.5381463297518394029, 0.2950988985880138027, -0.2496831530909939811, -0.9222662105458924175, 0.03027039329457266101, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "BROWSERITEM", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "BROWSERITEM", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "BROWSERITEM", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("CHIMNEY SUPPORT-1@AssemChimney1.3M", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
comp = Part.SelectionManager.GetSelectedObject3(1)
matChangingModel = comp.GetModelDoc()
matChangingModel.SetMaterialPropertyName2 "Default", "C:/PROGRA~1/SOLIDW~1/SOLIDW~1/lang/english/sldmaterials/SOLIDWORKS Materials.sldmat", "Alloy Steel"
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.106519625910779181, 0.673962555650933326, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.03744236420282962691, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.03744236420282962691, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03744236420282962691, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04493083704339555229, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01497694568113185076, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1273040382896207245, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1198155654490548061, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06739625556509333537, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05990778272452740305, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05241930988396147767, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1198155654490548061, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1347925111301866707, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06739625556509333537, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.08986167408679110458, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05241930988396147767, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02246541852169777614, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02995389136226370153, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007488472840565925381, -0.5184594575938490379, 12.22107990631224084, 0.4508228056322423072

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Zoom In/Out
Set swModelView = Part.ActiveView
swModelView.ZoomByFactor 1.964019558129474818
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1237002107350983759, -0.1797233481735822092, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.02246541852169777614, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.05990778272452740305, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.03744236420282962691, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007488472840565925381, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02246541852169777614, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007488472840565925381, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.007488472840565925381, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007488472840565925381, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.007488472840565925381, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, 0.3563871880293163485, 16.83627544710199686, -0.5107597732538238233

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Zoom In/Out
Set swModelView = Part.ActiveView
swModelView.ZoomByFactor 0.9350935093509350482

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy -0.0316130533484676457, 0.01421362088535755089

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy -0.0004901248581157775308, 0.01298830874006810451
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Part.ClearSelection2 True

' Save As
longstatus = Part.SaveAs3("D:\MS_Control_Project\SolidWorks\Stack\stack-1-3x30m-1.snapshot.1\AssemChimney1.3M.STEP", 0, 0)

' Save As
longstatus = Part.SaveAs3("D:\MS_Control_Project\SolidWorks\Stack\stack-1-3x30m-1.snapshot.1\AssemChimney1.3M.SLDASM", 0, 2)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
